language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint python-coveralls
script:
  - pylint --output-format=colorized --errors-only transaction
  - mypy --ignore-missing-imports --show-error-context ./transaction/*.py 
  - pytest
  - coverage run --source=transaction/ --module pytest
  - coveralls
