language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint
script:
  - pylint --output-format=colorized --errors-only transaction 
  - pytest
  - coverage run --source=transaction/ --module pytest
  - coveralls
